export const siteConfig = {
  projectName: "NASU",
  ticker: "$NASU",
  chainName: "Robinhood Chain",
  contractAddress: "CONTRACT_ADDRESS",
  contractExplorerUrl: null as string | null,
  tradeUrl: "#transparency",
  fundraiserUrl: "https://next.privat24.ua/env/donate/b2188461",
  officialStatementUrl: "#source-unavailable",
  developerRewards: "100%",
  totalDonated: null as number | null,
  donationCurrency: null as string | null,
  latestTransfer: null as null | { amount: number; currency: string; date: string; txUrl?: string },
  donationDataSource: "unavailable" as const,
  donationUpdatedAt: null as string | null,
  heroVideo: "/media/nasu-hero.mp4",
  heroPoster: "/media/nasu-hero-poster.jpg",
  heroMediaCredit: null as string | null,
  heroMediaSourceUrl: null as string | null,
} as const;
