import { siteConfig } from "@/src/config/site.config";
import { Navbar } from "./Navbar";

export function Hero() {
  const tradeIsExternal = siteConfig.tradeUrl.startsWith("http");
  return <section className="hero" id="top" aria-labelledby="hero-title">
    <video className="hero-video" autoPlay muted loop playsInline preload="metadata" poster={siteConfig.heroPoster} aria-hidden="true"><source src={siteConfig.heroVideo} type="video/mp4" /></video>
    <div className="hero-inner frame">
      <Navbar />
      <div className="hero-copy">
        <h1 className="display" id="hero-title">They hit science.<br />We rebuild it.</h1>
        <div className="hero-grid">
          <div>
            <p className="hero-description">On September 28, 2026, the Presidium of the National Academy of Sciences of Ukraine in Kyiv was struck during a Russian attack.</p>
            <p className="hero-description">NASU turns developer rewards generated by {siteConfig.ticker} into support for reconstruction.</p>
          </div>
          <div className="hero-actions">
            <a className="button button--solid" href={siteConfig.tradeUrl} {...(tradeIsExternal ? { target: "_blank", rel: "noopener noreferrer" } : {})}>Trade NASU</a>
            <a className="button" href={siteConfig.fundraiserUrl} target="_blank" rel="noopener noreferrer">Donate directly</a>
          </div>
        </div>
      </div>
      <div className="hero-meta eyebrow"><p>28.09.2026</p><p>Kyiv, Ukraine</p><p className="scroll-mark"><span className="scroll-line" />Scroll to the record</p></div>
    </div>
  </section>;
}
