import { ContractAddress } from "./ContractAddress";
import { siteConfig } from "@/src/config/site.config";
import type { DonationData } from "@/src/lib/donations/types";

function money(value: number | null, currency: string | null) {
  if (value === null || !currency) return null;
  return new Intl.NumberFormat("en", { style: "currency", currency }).format(value);
}

export function HowToHelp({ data }: { data: DonationData }) {
  const tradeExternal = siteConfig.tradeUrl.startsWith("http");
  const total = money(data.totalDonated, data.currency);
  const latest = data.latestTransfer ? `${data.latestTransfer.amount.toLocaleString("en")} ${data.latestTransfer.currency} · ${data.latestTransfer.date}` : null;
  return <section className="help section" id="help" aria-labelledby="help-title"><div className="frame">
    <header className="help-intro"><p className="kicker">What we can do now</p><h2 id="help-title">Two ways to help rebuild.</h2><p>NASU is an independent community initiative created to help channel support toward the reconstruction effort. You can donate directly, or participate through {siteConfig.ticker}, where 100% of developer rewards are designated for reconstruction.</p></header>
    <div className="choices">
      <article className="choice choice-donate"><div className="choice-number">01</div><div><p className="choice-label">The simplest path</p><h3>Donate directly</h3><p>If you simply want to help, you do not need to buy or trade anything. Donate directly through the official PrivatBank fundraiser supporting the reconstruction effort.</p><a className="button button-dark" href={siteConfig.fundraiserUrl} target="_blank" rel="noopener noreferrer">Donate via PrivatBank ↗</a></div></article>
      <article className="choice choice-token"><div className="choice-number">02</div><div><p className="choice-label">For crypto participants</p><h3>Trade {siteConfig.ticker}</h3><p>For people who participate in crypto markets, NASU provides another way to contribute. {siteConfig.ticker} is a token on {siteConfig.chainName}. Its developer rewards are designated to be converted and sent to the reconstruction fundraiser.</p><div className="reward"><strong>100%</strong><span>of developer rewards<br />for reconstruction</span></div><p className="flowline">Trading → Developer rewards → Conversion → Reconstruction fund</p><p className="flow-note">Every developer reward generated by the project is designated for reconstruction.</p><a className="button button-outline" href={siteConfig.tradeUrl} {...(tradeExternal ? { target: "_blank", rel: "noopener noreferrer" } : {})}>Trade {siteConfig.ticker} ↗</a><div className="contract-block"><span className="choice-label">Contract</span><ContractAddress /></div></div></article>
    </div>
    <aside className="transparency" aria-label="Transparency"><div><p className="kicker">Transparency</p><p>Verified transfers only. Manual or unavailable data is never presented as live.</p></div><dl><div><dt>Total sent to reconstruction</dt><dd>{total ?? "Awaiting first verified transfer"}</dd></div>{latest && <div><dt>Last transfer</dt><dd>{latest}</dd></div>}</dl></aside>
  </div></section>;
}
