import { siteConfig } from "@/src/config/site.config";

export function Mission() {
  return <section className="mission section" id="mission" aria-labelledby="mission-title"><div className="frame">
    <div className="mission-head"><p className="eyebrow">The response</p><h2 className="section-title" id="mission-title">Turn trading into rebuilding.</h2></div>
    <p className="mission-copy body-lg">NASU is an independent community initiative built around a simple idea: use the developer rewards generated by {siteConfig.ticker} to support reconstruction.</p>
    <div className="commitment"><div className="hundred">100%</div><div className="commitment-copy"><strong>Of developer rewards<br />to reconstruction</strong><p>100% of developer rewards generated by {siteConfig.ticker} are designated to be converted and donated to the official reconstruction fundraiser linked by this project.</p></div></div>
  </div></section>;
}
